### ISSUE TITLE
iOS8 compatibility

### ISSUE THREAD

**Issue by klefevre** [AliSoftware/OHAlertView#3]
Hi, have you considered to port OHAlertView on iOS8 ?
If yes, do you have a plan to achieve that goal ?
Otherwise, should we think about use an other solution ?

Since UIAlertView is now deprecated for UIAlertController... Have you an idea how to make OHAlertView (and OHActionSheet) fully compatible with iOS8 ?

Regards,
KL

**Comment by AliSoftware** [comment]
Was about time, but `3.0.0` is out with `UIAlertController` support (and still using `UIAlertView` if you are targeting iOS < 8.0)
