### ISSUE TITLE
Unrecognized selector send to instance [...] textFieldDidChange on iOS8+

### ISSUE THREAD

**Issue by nonoclark** [AliSoftware/OHAlertView#7]
Hi,

I noticed a crash on OHAlertView on iOS8 and above.
I got an _unrecognized selector send to instance [...] -textFieldDidChange [...]_. 

The reproducing process is to show an OHAlertView (without any textfield inside it). 
Once dismissed, I present a new screen with one or more textfields. 

The textFieldDidChange events of any of these textfields are caught by OHAlertView via the NSNotificationCenter event, but no more OHAlertView instance were still alive at this time.

"It's a trap !" :)

**Comment by AliSoftware** [comment]
Please make it a PR, I'm not gonna be able to  investigate this anytime  soon

**Comment by bill350** [comment]
@nonoclark I've created a PR https://github.com/AliSoftware/OHAlertView/pull/8 to fix this, can you confirm that you not reproduce this issue anymore ?

Thanks.
